[package]
name = "ipv6-placer"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = true
overflow-checks = false
panic = "abort"
strip = "symbols"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
image = "0.24"
num_cpus = "1.16"
socket2 = "0.5"
